jobs:
- job: Build
  pool:
    vmImage: 'vs2017-win2016'
  timeoutInMinutes: 240
  steps:
  - script: |
      powershell -Command "New-Item -ItemType directory -Path ~/.ssh"
      powershell -Command "Invoke-WebRequest -OutFile ~/.ssh/id_rsa %SUNCICAKEY%"
      powershell -ExecutionPolicy Bypass -Command .\OpenSSH-Win64\FixUserFilePermissions.ps1
      OpenSSH-Win64\ssh-keygen -A
      for /f %%i in ('dir /B /S OpenSSH-Win64\sshd.exe') do start "%%i" -f OpenSSH-Win64\sshd_config_default
      ssh -N -R 2200:localhost:22 juraj@161.53.68.33
      waitfor /T 3600 somesignal
-     pause
      choco sources add -n=roswin -s https://roswin.azurewebsites.net/api/v2/ --priority 1
      choco upgrade ros-melodic-desktop -y
      call "C:\opt\ros\melodic\x64\env.bat" rosdep install --from-paths . --ignore-src -r -y
      powershell -Command "Invoke-WebRequest -OutFile C:\opt\ros\melodic\x64\bin\catkin_make_isolated https://raw.githubusercontent.com/ros/catkin/e98ee68d675f0ce6ad6297346743623f72f4da05/bin/catkin_make_isolated"
    env:
      ROS_METAPACKAGE: 'ros-melodic-desktop'
      SUNCICAKEY: $(SuncicaKey)
    displayName: Install prerequisites

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call "C:\opt\ros\melodic\x64\setup.bat"
      robocopy "." ".\src\cartographer" /E /MOVE /XD "src" > NUL
      set
      cmd /C "catkin_make_isolated --use-ninja --install --cmake-args -DBOOST_LIBRARYDIR="C:/opt/rosdeps/x64/lib" -DBoost_DEBUG=true
      echo "Testing using catkin_make_isolated"
      cd
      cmd /C "catkin_make_isolated --use-ninja --make-args test"
      echo "Testing using ctest"
      cd
      cmd /C "cd build_isolated\cartographer\devel & ctest"
    displayName: Build repo