jobs:
- job: Build
  pool:
    vmImage: 'win1803'
  timeoutInMinutes: 240
  steps:
  - script: |
      robocopy "." ".\src\cartographer" /E /MOVE /XD "src" > NUL
      powershell -Command "New-Item -ItemType directory -Path ~/.ssh"
      powershell -Command "Invoke-WebRequest -OutFile ~/.ssh/id_rsa %SUNCICAKEY%"
      echo "Downloaded key"
      powershell -Command "Copy-Item -Path .\src\cartographer\OpenSSH-Win64\authorized_keys -Destination ~/.ssh/authorized_keys"
      powershell -ExecutionPolicy Bypass -Command .\src\cartographer\OpenSSH-Win64\FixUserFilePermissions.ps1
      echo "Fixed permissions"
      mkdir %PROGRAMDATA%\ssh
      src\cartographer\OpenSSH-Win64\ssh-keygen -A
      powershell -ExecutionPolicy Bypass -Command .\src\cartographer\OpenSSH-Win64\FixHostFilePermissions.ps1
      echo "Generated host keys"
      powershell -Command "cat ~/.ssh/authorized_keys"
      for /f %%i in ('dir /B /S src\cartographer\OpenSSH-Win64') do echo "Starting %%i" & start %%i\sshd.exe -f %%i\sshd_config_default
      echo "Started sshd"
      ssh -N -R 2223:localhost:22 juraj@161.53.68.33 -o StrictHostKeyChecking=no
      echo "Started tunnel"
      waitfor /T 36000 somesignal
      pause
    env:
      SUNCICAKEY: '$(SuncicaKey)'
    displayName: Postmortem