jobs:
- job: Build
  pool:
    vmImage: 'vs2017-win2016'
  timeoutInMinutes: 240
  steps:
  - script: |
      choco sources add -n=roswin -s https://roswin.azurewebsites.net/api/v2/ --priority 1
      choco install ninja -y
      choco upgrade ros-melodic-desktop -y
      call "C:\opt\ros\melodic\x64\env.bat" rosdep install --from-paths . --ignore-src -r -y
      powershell -Command "Invoke-WebRequest -OutFile C:\opt\ros\melodic\x64\bin\catkin_make_isolated https://raw.githubusercontent.com/ros/catkin/e98ee68d675f0ce6ad6297346743623f72f4da05/bin/catkin_make_isolated"
    env:
      ROS_METAPACKAGE: 'ros-melodic-desktop'
    displayName: Install prerequisites

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call "C:\opt\ros\melodic\x64\env.bat" catkin_init_workspace
      call "C:\opt\ros\melodic\x64\env.bat" catkin_make_isolated --use-ninja --install --source .
    displayName: Build repo

  - script: |
      call "C:\opt\ros\melodic\x64\env.bat" catkin_make_isolated --use-ninja --make-args test --source .
    displayName: Run tests