resources:
  repositories:
    - repository: templates
      type: github
      name: larics/rosonwindows_ci
      endpoint: larics

jobs:
- template: build.yml@templates  # Template reference
  parameters:
    ros_metapackage: 'ros-melodic-desktop'